version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
    command: sh -c "python app/seed.py && flask run"