version: '3.8'

services:
  flask-api:
    build: .
    env_file:
      - .env.dev
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
      - FLASK_APP=app

    command: flask run